version: 2
updates:
  # 🔹 Java/Maven Dependencies (Automatically covers multiple services)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
    assignees:
      - "leo-wag"
    reviewers:
      - "leo-wag"
    target-branch: "develop"
    allow:
      - dependency-type: "all"  # Ensure all updates are considered

  # 🔹 Automatically apply the same config for all `ms-*` backend services
  - package-ecosystem: "maven"
    directory: "/microservices/user-service"
    schedule:
      interval: "weekly"
      time: "08:00"
    assignees:
      - "leo-wag"
    reviewers:
      - "leo-wag"
    target-branch: "develop"

  - package-ecosystem: "maven"
    directory: "/microservices/post-service"
    schedule:
      interval: "weekly"
      time: "08:00"
    assignees:
      - "leo-wag"
    reviewers:
      - "leo-wag"
    target-branch: "develop"

  # 🔹 Frontend Dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      time: "08:00"
    assignees:
      - "jnsgbl"
    reviewers:
      - "jnsgbl"
    target-branch: "develop"

  # 🔹 GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
    assignees:
      - "polatmete"
    reviewers:
      - "polatmete"
    target-branch: "develop"
