services:
  localstack:
    image: localstack/localstack-pro
    container_name: localstack
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=cognito-idp
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
      - "127.0.0.1:8443:443"              # HTTPS Gateway (Pro feature)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"

  terraform:
    image: hashicorp/terraform
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform
    entrypoint: [ "/bin/sh", "/terraform/init-terraform.sh" ]
    depends_on:
      - localstack