networks:
  localstack_network:
    driver: bridge

services:
  localstack:
    image: localstack/localstack-pro
    container_name: localstack
    hostname: localstack
    profiles: [ dev, deploy, prod ]
    networks:
      - localstack_network
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=secretsmanager, iam, sts, cognito-idp, dynamodb, s3, ecs, elbv2, ec2, ses, lambda, cloudcontrol, apigateway, events, sns, sqs, logs
      - SMTP_HOST=mailhog:1025
      - SMTP_EMAIL=sender@example.com
      - LOCALSTACK_HOST=localstack
      - DISABLE_CORS_CHECKS=1
      - DYNAMODB_REMOVE_EXPIRED_ITEMS=1
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
      - "8443:443"             # HTTPS Gateway
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"

  terraform:
    build:
      context: ./terraform
      dockerfile: Dockerfile
    image: hashicorp/terraform
    container_name: terraform
    profiles: [ dev, prod ]
    working_dir: /terraform
    networks:
      - localstack_network
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_HOSTNAME=localstack
      - EDGE_PORT=4566
      - S3_HOSTNAME=localstack
    depends_on:
      - localstack
    volumes:
      - ./terraform:/terraform
      - ./lambda-functions:/lambda-functions
      - ./microservices:/microservices
      - ./frontend:/frontend
    entrypoint: [ "/bin/sh", "/terraform/init-terraform.sh" ]
    restart: "no"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    hostname: mailhog
    profiles: [ dev, prod ]
    networks:
      - localstack_network
    ports:
      - "8025:8025"
      - "1025:1025"

  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    container_name: deploy
    profiles: [ deploy, prod ]
    networks:
      - localstack_network
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - BUCKET_NAME=dailygrind
    depends_on:
      - localstack
    volumes:
      - ./microservices:/microservices
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
