services:
  localstack:
    image: localstack/localstack-pro
    profiles: [dev, fe-dev, prod]
    container_name: localstack
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=iam, sts, cognito-idp, dynamodb, s3
      - SMTP_HOST=1025
      - SMTP_EMAIL=sender@example.com
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
      - "8443:443"              # HTTPS Gateway
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"

  mailhog:
    image: mailhog/mailhog
    profiles: [dev, fe-dev, prod]
    ports:
      - "8025:8025"
      - "1025:1025"

  ms-user:
    build: ./ms-user
    profiles: [fe-dev, prod]
#    ports:
#      - "8080:8080"
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - SERVER_PORT=8080

  ms-post:
    build: ./ms-post
    profiles: [fe-dev, prod]
#    ports:
#      - "8081:8080"
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - SERVER_PORT=8080

  ms-push-notification:
    build: ./ms-push-notification
    profiles: [fe-dev, prod]
    ports:
      - "8082:8080"
    depends_on:
      - localstack
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - SERVER_PORT=8080

  frontend:
    build: ./ms-frontend
    profiles: [prod]
    ports:
      - "3000:80"


#  terraform:
#    image: hashicorp/terraform
#    working_dir: /terraform
#    volumes:
#      - ./terraform:/terraform
#    environment:
#      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
#    entrypoint: [ "/bin/sh", "/terraform/init-terraform.sh" ]
#    depends_on:
#      - localstack
