import { User } from '../types/user';

export const mockProfiles: User[] = [
  {
    userId: '1',
    email: 'alice@gmail.com',
    firstName: 'Alice',
    lastName: 'All',
    birthday: '1990-01-01',
    location: 'New York',
    jobs: [
      {
        jobId: '1',
        startDate: '2015-01-01',
        endDate: '2020-01-01',
        jobTitle: 'Software Engineer',
        companyName: 'Tech Company',
        location: 'New York',
        description: 'Developed software solutions.',
      },
      {
        jobId: '2',
        startDate: '2020-02-01',
        endDate: '2023-01-01',
        jobTitle: 'Senior Software Engineer',
        companyName: 'Another Tech Company',
        location: 'New York',
        description: 'Led a team of developers.',
      },
    ],
    education: [
      {
        educationId: '1',
        degree: 'Bachelor of Science in Computer Science',
        institution: 'University of Technology',
        educationStartDate: '2008-01-01',
        educationEndDate: '2012-01-01',
        fieldOfStudy: 'Computer Science',
        educationLocation: 'New York',
        educationDescription: 'Studied computer science and software engineering.',
      },
    ],
  },
  {
    userId: '2',
    email: 'bob@gmail.com',
    firstName: 'Bob',
    lastName: 'Builder',
    birthday: '1985-05-05',
    location: 'Los Angeles',
    jobs: [
      {
        jobId: '1',
        startDate: '2010-01-01',
        endDate: '2015-01-01',
        jobTitle: 'Construction Worker',
        companyName: 'Build It Inc.',
        location: 'Los Angeles',
        description: 'Worked on various construction projects.',
      },
      {
        jobId: '2',
        startDate: '2015-02-01',
        endDate: '2023-01-01',
        jobTitle: 'Site Supervisor',
        companyName: 'Build It Inc.',
        location: 'Los Angeles',
        description: 'Supervised construction sites and managed teams.',
      },
    ],
    education: [
      {
        educationId: '1',
        degree: 'Diploma in Construction Management',
        institution: 'Los Angeles Community College',
        educationStartDate: '2005-01-01',
        educationEndDate: '2007-01-01',
        fieldOfStudy: 'Construction Management',
        educationLocation: 'Los Angeles',
        educationDescription: 'Studied construction management and project planning.',
      },
    ],
  },
  {
    userId: '3',
    email: 'charlie@gmail.com',
    firstName: 'Charlie',
    lastName: 'Chaplin',
    birthday: '1992-03-03',
    location: 'Chicago',
    jobs: [
      {
        jobId: '1',
        startDate: '2018-01-01',
        endDate: '2020-01-01',
        jobTitle: 'Graphic Designer',
        companyName: 'Design Studio',
        location: 'Chicago',
        description: 'Created visual concepts and designs.',
      },
      {
        jobId: '2',
        startDate: '2020-02-01',
        endDate: '2023-01-01',
        jobTitle: 'Art Director',
        companyName: 'Creative Agency',
        location: 'Chicago',
        description: 'Led design projects and managed a team of designers.',
      },
    ],
    education: [
      {
        educationId: '1',
        degree: 'Bachelor of Arts in Graphic Design',
        institution: 'Chicago Art Institute',
        educationStartDate: '2010-01-01',
        educationEndDate: '2014-01-01',
        fieldOfStudy: 'Graphic Design',
        educationLocation: 'Chicago',
        educationDescription: 'Studied graphic design and visual communication.',
      },
    ],
  },
  {
    userId: '4',
    email: 'diane@gmail.com',
    firstName: 'Diane',
    lastName: 'Davis',
    birthday: '1988-07-07',
    location: 'Miami',
    jobs: [
      {
        jobId: '1',
        startDate: '2012-01-01',
        endDate: '2016-01-01',
        jobTitle: 'Marketing Specialist',
        companyName: 'Marketing Agency',
        location: 'Miami',
        description: 'Developed marketing strategies and campaigns.',
      },
      {
        jobId: '2',
        startDate: '2016-02-01',
        endDate: '2023-01-01',
        jobTitle: 'Marketing Manager',
        companyName: 'Global Marketing Inc.',
        location: 'Miami',
        description: 'Managed marketing teams and projects.',
      },
    ],
    education: [
      {
        educationId: '1',
        degree: 'Bachelor of Business Administration',
        institution: 'Miami University',
        educationStartDate: '2006-01-01',
        educationEndDate: '2010-01-01',
        fieldOfStudy: 'Marketing',
        educationLocation: 'Miami',
        educationDescription: 'Studied business administration and marketing.',
      },
    ],
  },
];
