dg:
  us:
    cors:
      allowed-origins: http://localhost:3000, https://oauth.pstmn.io/v1/callback
      allowed-methods: GET, POST, PUT, DELETE
    aws:
      region: ${AWS_REGION:us-east-1}
      port: ${LOCALSTACK_PORT:4566}
      access-key: ${AWS_DYNAMODB_ACCESS_KEY_ID:test}
      secret-key: ${AWS_DYNAMODB_SECRET_ACCESS_KEY:test}
      base-url: http://localhost:${dg.us.aws.port}
      cognito:
        user-pool-id: ${AWS_COGNITO_USER_POOL_ID:us-east-1_09be8b5020104c808c97f23a22ae1e50}
        issuer-uri: http://localstack:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}
        jwk-set-uri: http://localhost:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}/.well-known/jwks.json
      sqs:
        queue-url: ${AWS_SQS_QUEUE_URL:${dg.us.aws.base-url}/000000000000/user-events-consumer-queue}

spring:
  application:
    name: postService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${dg.us.aws.cognito.issuer-uri}
          jwk-set-uri: ${dg.us.aws.cognito.jwk-set-uri}

server:
  port: ${PORT:8081}
