export const inspireMeData = [
  'What conversation made you think deeper today?',
  'How did you help someone grow or succeed today?',
  'What is a question you asked today that led to a valuable answer?',
  'Describe a moment where you practiced active listening.',
  'What is something you saw today that challenged your perspective?',
  'How did you step out of your comfort zone today?',
  'What feedback did you give or receive that mattered?',
  'What is a leadership lesson you observed or practiced today?',
  'How did you turn a setback into something constructive today?',
  'What is one thing you did today that your future self will thank you for?',
  'What is one thing you learned today that surprised you?',
  'Share a small win or insight from your workday.',
  'What challenge did you overcome today, and how?',
  'Describe a moment today where you felt curious or inspired.',
  'What is one tip or trick you discovered that could help others?',
  'Reflect on something someone taught you today.',
  'What is one mistake you made today—and what did you learn from it?',
  'Share a quote or idea that resonated with you today.',
  'What is one habit or mindset shift you’re working on?',
  'What did you see today that made you think differently?',
];
