dg:
  us:
    cors:
      allowed-origins: http://localhost:3000, https://oauth.pstmn.io/v1/callback, http://localhost:8081
      allowed-methods: GET, POST, PUT, DELETE
    aws:
      region: ${AWS_REGION:us-east-1}
      port: ${LOCALSTACK_PORT:4566}
      access-key: ${AWS_DYNAMODB_ACCESS_KEY_ID:test}
      secret-key: ${AWS_DYNAMODB_SECRET_ACCESS_KEY:test}
      base-url: http://localhost:${dg.us.aws.port}
      cognito:
        user-pool-id: ${AWS_COGNITO_USER_POOL_ID:us-east-1_de7d439c918046768a26c1934078dbec}
        issuer-uri: http://localstack:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}
        jwk-set-uri: http://localhost:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}/.well-known/jwks.json
      sns:
        topic-arn: ${AWS_SNS_TOPIC_ARN:arn:aws:sns:us-east-1:000000000000:user-events-topic}

spring:
  application:
    name: userService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${dg.us.aws.cognito.issuer-uri}
          jwk-set-uri: ${dg.us.aws.cognito.jwk-set-uri}
server:
  port: ${PORT:8080}

api:
  base-path: /users

