package com.uzh.ase.dailygrind.pushnotificationsservice.pushNotification.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.uzh.ase.dailygrind.pushnotificationsservice.pushNotification.controller.dto.SubscriptionDto;
import com.uzh.ase.dailygrind.pushnotificationsservice.pushNotification.repository.SubscriptionDtoConverter;
import lombok.*;

@DynamoDBTable(tableName = "push-subscriptions")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PushSubscription {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "subscription_id")
    private String subscriptionId;

    @DynamoDBAttribute(attributeName = "user_id")
    private String userId;

    @DynamoDBAttribute(attributeName = "push_subscription")
    private SubscriptionDto pushSubscription;

    // Explicit getter with proper annotations
    @DynamoDBTypeConverted(converter = SubscriptionDtoConverter.class)
    public SubscriptionDto getPushSubscription() {
        return pushSubscription;
    }

    // Optional: you can also add a setter if needed
    public void setPushSubscription(SubscriptionDto pushSubscription) {
        this.pushSubscription = pushSubscription;
    }
}
