dg:
  us:
    cors:
      allowed-origins: http://localhost:3000, http://localhost:30001, http://localhost:4566, http://localstack:4566, https://oauth.pstmn.io/v1/callback
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    aws:
      region: ${AWS_REGION:us-east-1}
      port: ${LOCALSTACK_PORT:4566}
      access-key: ${AWS_DYNAMODB_ACCESS_KEY_ID:test}
      secret-key: ${AWS_DYNAMODB_SECRET_ACCESS_KEY:test}
      base-url: http://${AWS_HOSTNAME:localhost}:${dg.us.aws.port}
      cognito:
        user-pool-id: ${AWS_COGNITO_USER_POOL_ID:us-east-1_XXXXXXXX}
        issuer-uri: http://localstack:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}
        jwk-set-uri: http://${AWS_HOSTNAME:localhost}:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}/.well-known/jwks.json

  lambda:
    function-name: ${LAMBDA_FUNCTION_NAME:pushNotificationLambda}

spring:
  application:
    name: push-notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${dg.us.aws.cognito.issuer-uri}
          jwk-set-uri: ${dg.us.aws.cognito.jwk-set-uri}

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

server:
  port: ${PORT:8081}

