dg:
  us:
    cors:
      allowed-origins: http://localhost:3000, https://oauth.pstmn.io/v1/callback
      allowed-methods: GET, POST, PUT, DELETE
    aws:
      region: ${AWS_REGION:us-east-1}
      port: ${LOCALSTACK_PORT:4566}
      access-key: ${AWS_DYNAMODB_ACCESS_KEY_ID:test}
      secret-key: ${AWS_DYNAMODB_SECRET_ACCESS_KEY:test}
      base-url: http://localhost.localstack.cloud:${dg.us.aws.port}
      cognito:
        user-pool-id: ${AWS_COGNITO_USER_POOL_ID:us-east-1_ec029cc3670d4ec0b97aa80ac3ddea9e}
        issuer-uri: http://localhost.localstack.cloud:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}
        jwk-set-uri: http://localhost:${dg.us.aws.port}/${dg.us.aws.cognito.user-pool-id}/.well-known/jwks.json

spring:
  application:
    name: push-notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${dg.us.aws.cognito.issuer-uri}
          jwk-set-uri: ${dg.us.aws.cognito.jwk-set-uri}

server:
  port: ${PORT:8082}

logging:
  level:
    org.springframework.security: TRACE
