name: Backend CI

on:
  push:
    branches:
      - develop
      - "feature/*"
      - "release/*"
      - "hotfix/*"
  pull_request:
    branches:
      - develop
      - "release/*"
      - "hotfix/*"

jobs:
  discover-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Backend Services
        id: set-matrix
        run: |
          SERVICES=$(ls -d ms-* 2>/dev/null | grep -v 'ms-frontend' | jq -R -s -c 'split("\n")[:-1]')
          echo "Detected services: $SERVICES"
          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"

  test-backend:
    name: Build & Test Backend Services
    runs-on: ubuntu-latest
    needs: discover-services
    strategy:
      matrix:
        service: ${{ fromJson(needs.discover-services.outputs.services) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build and test with Maven
        working-directory: ${{ matrix.service }}
        run: mvn clean verify -Pintegration-tests
