spring:
  application:
    name: userService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost.localstack.cloud:4566/us-east-1_573e2e5b87e8442696d15c7fe168b791
          jwk-set-uri: http://localhost:4566/us-east-1_573e2e5b87e8442696d15c7fe168b791/.well-known/jwks.json

logging:
  level:
    org.springframework.security: TRACE